version: "3.9"
services:
  go:
    build: .
    links:
      - db
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: