version: "3.9"
services:
  go:
    build: .
    links:
      - db
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gorm-test
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: